[preferred]
# Necessary for niri screen sharing to work at all
default=gnome;gtk;

# Force the file picker and app chooser to GTK 
# (This allows us to force them to be Dark/Catppuccin via gsettings)
org.freedesktop.impl.portal.FileChooser=kde;gtk;
org.freedesktop.impl.portal.AppChooser=kde;gtk;
org.freedesktop.impl.portal.Access=gtk;

# THEME SETTINGS: Let KDE try to provide your Catppuccin colors
org.freedesktop.impl.portal.Settings=kde;gtk;

# secrets
org.freedesktop.impl.portal.Secret=kwallet