[preferred]
default=gtk

# Force the app chooser to KDE
org.freedesktop.impl.portal.AppChooser=kde;gtk
# THEME SETTINGS: Let KDE try to provide your Catppuccin colors
org.freedesktop.impl.portal.Settings=kde;gtk

# screen cast, necessary for screen sharing
org.freedesktop.impl.portal.ScreenCast=gnome
org.freedesktop.impl.portal.RemoteDesktop=gnome
