[preferred]
# Use KDE for everything by default
default=kde;gtk;

# Specific overrides
org.freedesktop.impl.portal.Secret=kwallet
org.freedesktop.impl.portal.FileChooser=kde
org.freedesktop.impl.portal.Notification=kde
org.freedesktop.impl.portal.Access=gtk;

# Gnome for screencasting 
org.freedesktop.impl.portal.Screencast=gnome
org.freedesktop.impl.portal.Screenshot=gnome