export const SYMLINK_ITEMS = [
  "btop",
  ["hyprland", "hypr"],
  "gammastep",
  "niri",
  "swayidle",
  "swaylock",
  "kitty",
  "rofi",
  "swaync",
  "waybar",
  "autostart",
  "wlogout",
  "starship.toml",
  "xdg-desktop-portal",
  ["coolwall.js", "coolwall.js", "local"],
  ["scripts", "scripts", "local"],
  ["wall", "wall", "pictures"],
  "gtk-3.0",
  "gtk-4.0",
  "mimeapps.list",
  "nvim",
  "systemd/user",
  [".bashrc", ".bashrc", "home"],
  [".zshrc", ".zshrc", "home"],
  [".shared.sh", ".shared.sh", "home"],
  [".uxplayrc", ".uxplayrc", "home"],
  [".gitconfig", ".gitconfig", "home"],
];
