color_base #1e1e2e
color_mantle #181825
color_crust #11111b
color_text #cdd6f4
color_subtext0 #a6adc8
color_subtext1 #bac2de
color_surface0 #313244
color_surface1 #45475a
color_surface2 #585b70
color_overlay0 #6c7086
color_overlay1 #7f849c
color_overlay2 #9399b2
color_blue #89b4fa
color_lavender #b4befe
color_sapphire #74c7ec
color_sky #89dceb
color_teal #94e2d5
color_green #a6e3a1
color_yellow #f9e2af
color_peach #fab387
color_maroon #eba0ac
color_red #f38ba8
color_mauve #cba6f7
color_pink #f5c2e7
color_flamingo #f2cdcd
color_rosewater #f5e0dc

background #4e1e2e
foreground #cdd6f4
selection_background #f5e0dc
selection_foreground #1e1e2e
cursor #f5e0dc
