color_base #1e1e2e
# base
color_mantle #181825
# mantle
color_crust #11111b
# crust
color_text #cdd6f4
# text
color_subtext0 #a6adc8
# subtext0
color_subtext1 #bac2de
# subtext1
color_surface0 #313244
# surface0
color_surface1 #45475a
# surface1
color_surface2 #585b70
# surface2
color_overlay0 #6c7086
# overlay0
color_overlay1 #7f849c
# overlay1
color_overlay2 #9399b2
# overlay2
color_blue #89b4fa
# blue
color_lavender #b4befe
# lavender
color_sapphire #74c7ec
# sapphire
color_sky #89dceb
# sky
color_teal #94e2d5
# teal
color_green #a6e3a1
# green
color_yellow #f9e2af
# yellow
color_peach #fab387
# peach
color_maroon #eba0ac
# maroon
color_red #f38ba8
# red
color_mauve #cba6f7
# mauve
color_pink #f5c2e7
# pink
color_flamingo #f2cdcd
# flamingo
color_rosewater #f5e0dc
# rosewater
background #1e1e2e
foreground #cdd6f4
selection_background #f5e0dc
selection_foreground #1e1e2e
cursor #f5e0dc
