include generated-colors.conf

# Font Configuration
font_family      MonaspiceNe Nerd Font
font_size        8
bold_font        auto
text_composition_strategy 1.0 0
italic_font      auto
bold_italic_font auto


# Window Configuration
window_padding_width 8
background_opacity 1.0
background_blur 32
hide_window_decorations yes

# Scrollback
scrollback_lines 3000

# Cursor Configuration
cursor_shape block
cursor_blink_interval 1
mouse_hide_wait  2.0
cursor_shape     block

# Terminal features
copy_on_select yes
strip_trailing_spaces smart
url_color        #0087bd
url_style        dotted

#Close the terminal without confirmation
confirm_os_window_close 0

# Key bindings for common actions
map ctrl+shift+n new_window
map ctrl+t new_tab
map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0

# Tab configuration
tab_bar_style powerline
tab_bar_align left

# Shell integration
shell_integration enabled

